from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    # Add email explicitly
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Apply Tailwind classes to every field generated by the form
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'w-full border p-3 rounded-lg border-slate-300 focus:ring-2 focus:ring-green-500 outline-none'
            })